/**
 * Copied from: https://github.com/tensorflow/tfjs-examples/blob/master/mobilenet/imagenet_classes.js
 */

/**
 * @license
 * Copyright 2017 Google LLC. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =============================================================================
 */

// I have reduced the classes to simple dog breeds
export const ImageNetClasses = {
  151: 'Chihuahua',
  152: 'Japanese Spaniel',
  153: 'Maltese Dog',
  154: 'Pekinese',
  155: 'Shih-Tzu',
  156: 'Blenheim Spaniel',
  157: 'Papillon',
  158: 'Toy Terrier',
  159: 'Rhodesian Ridgeback',
  160: 'Afghan Hound',
  161: 'Basset',
  162: 'Beagle',
  163: 'Bloodhound',
  164: 'Bluetick',
  165: 'Black-and-Tan Coonhound',
  166: 'Walker hound',
  167: 'English foxhound',
  168: 'Redbone',
  169: 'Borzoi',
  170: 'Irish Wolfhound',
  171: 'Italian Greyhound',
  172: 'Whippet',
  173: 'Ibizan Hound',
  174: 'Norwegian Elkhound',
  175: 'Otterhound',
  176: 'Saluki',
  177: 'Scottish Deerhound',
  178: 'Weimaraner',
  179: 'Staffordshire Bullterrier',
  180: 'American Staffordshire Terrier',
  181: 'Bedlington Terrier',
  182: 'Border Terrier',
  183: 'Kerry Blue Terrier',
  184: 'Irish Terrier',
  185: 'Norfolk Terrier',
  186: 'Norwich Terrier',
  187: 'Yorkshire Terrier',
  188: 'Wire-Haired fox Terrier',
  189: 'Lakeland Terrier',
  190: 'Sealyham Terrier',
  191: 'Airedale Terrier',
  192: 'Cairn Terrier',
  193: 'Australian Terrier',
  194: 'Dandie Dinmont Terrier',
  195: 'Boston Terrier',
  196: 'Miniature Schnauzer',
  197: 'Giant Schnauzer',
  198: 'Standard Schnauzer',
  199: 'Scotch Terrier',
  200: 'Tibetan Terrier',
  201: 'Silky terrier',
  202: 'Soft-coated Wheaten Terrier',
  203: 'West Highland White Terrier',
  204: 'Lhasa Apso',
  205: 'Flat-Coated Retriever',
  206: 'Curly-Coated Retriever',
  207: 'Golden Retriever',
  208: 'Labrador Retriever',
  209: 'Chesapeake Bay Retriever',
  210: 'German Short-haired Pointer',
  211: 'Hungarian Pointer',
  212: 'English Setter',
  213: 'Irish Setter',
  214: 'Gordon Setter',
  215: 'Brittany Spaniel',
  216: 'Clumber Spaniel',
  217: 'English Springer Spaniel',
  218: 'Welsh Springer Spaniel',
  219: 'English Cocker Spaniel',
  220: 'Sussex Spaniel',
  221: 'Irish Water Spaniel',
  222: 'Kuvasz',
  223: 'Schipperke',
  224: 'Groenendael',
  225: 'Malinois',
  226: 'Briard',
  227: 'Kelpie',
  228: 'Komondor',
  229: 'Old English Sheepdog',
  230: 'Shetland Sheepdog',
  231: 'Collie',
  232: 'Border Collie',
  233: 'Bouvier des Flandres',
  234: 'Rottweiler',
  235: 'German Shepherd',
  236: 'Doberman Pinscher',
  237: 'Miniature Pinscher',
  238: 'Greater Swiss Mountain Dog',
  239: 'Bernese Mountain Dog',
  240: 'Appenzeller',
  241: 'EntleBucher',
  242: 'Boxer',
  243: 'Bull Mastiff',
  244: 'Tibetan Mastiff',
  245: 'French Bulldog',
  246: 'Great Dane',
  247: 'Saint Bernard',
  248: 'Eskimo Dog',
  249: 'Malamute',
  250: 'Siberian husky',
  251: 'Dalmatian',
  252: 'Affenpinscher',
  253: 'Basenji',
  254: 'Pug',
  255: 'Leonberg',
  256: 'Newfoundland',
  257: 'Great Pyrenees',
  258: 'Samoyed',
  259: 'Pomeranian',
  260: 'Chow',
  261: 'Keeshond',
  262: 'Brabancon Griffon',
  263: 'Pembroke',
  264: 'Cardigan',
  265: 'toy poodle',
  266: 'Miniature Poodle',
  267: 'Standard Poodle',
  268: 'Mexican Hairless'
};
